name: Sauron.v1
channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - bioconductor-biomart=2.38
 - bioconductor-flowpeaks=1.28
 - bioconductor-genomeinfodbdata=1.2.0
 - bioconductor-scater=1.10
 - bioconductor-scran=1.10
 - bioconductor-singlecellexperiment=1.4
 - bioconductor-sva=3.30
 - r-base=3.5
 - r-biocmanager=1.30
 - r-data.table=1.11
 - r-dbscan=1.1
 - r-dplyr=0.8
 - r-fields=9.6
 - r-igraph=1.2
 - r-ineq=0.2
 - r-optparse=1.6
 - r-pheatmap=1.0
 - r-rafalib=1.0
 - r-rcolorbrewer=1.1
 - r-scales=1.0
 - r-seurat=3.0.1
 - r-vegan=2.5
 - r-umap=0.2
 - umap-learn=0.3.7
 - wget=1.19.4  # For compatibility with genomeinfodbdata (currently broken)
