channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - bioconductor-biomart=2.38
 - bioconductor-flowpeaks=1.28
 - bioconductor-scater=1.10
 - bioconductor-singlecellexperiment=1.4
 - bioconductor-sva=3.30
 - r-base=3.5
 - r-biocmanager=1.30
 - r-data.table=1.11
 - r-dplyr=0.8
 - r-fields=9.6
 - r-igraph=1.2
 - r-ineq=0.2
 - r-pheatmap=1.0
 - r-rafalib=1.0
 - r-rcolorbrewer=1.1
 - r-scales=1.0
 - r-seurat=2.3
 - r-vegan=2.5
