---
title: "Functions"
author: "Paulo Czarnewski"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    highlight: pygments
---
***
# Introduction
Here we give a deep understanting of the functions and parameters being used in the workflow. 

The first line 
```{bash, engine = 'bash', eval=F}
main="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $main/initialize.sh 2>&1 | tee $main/log/'initialize_log.txt'
```

The first line 
```{bash, engine = 'bash', eval=F}
main="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $main/initialize.sh 2>&1 | tee $main/log/'initialize_log.txt'
```


```{bash, engine = 'bash', eval=F}
var_to_plot='VARIABLE_COLUMNS_FROM_METADATA_TABLE'
var_to_regress='nFeature_RNA,percent_mito,S.Score,G2M.Score'
```


***
# Load datasets
```{bash, engine = 'bash', eval=F}
Rscript $script_path/00_load_data.R \
--input_path $main/'data' \
--dataset_metadata_path $main/'data/metadata.csv' \
--columns_metadata $var_to_plot \
--assay 'RNA' \
--output_path $main/'analysis/1_qc' \
2>&1 | tee $main/log/'00_load_data_log.txt'
```
#### `input_path`
#### `dataset_metadata_path`
#### `columns_metadata`
#### `assay`
#### `output_path`

***
# Run Quality Control
```{bash, engine = 'bash', eval=F}
Rscript $script_path/01_qc_filter.R \
--Seurat_object_path $main/'analysis/1_qc/raw_seurat_object.rds' \
--columns_metadata $var_to_plot \
--species_use 'mmusculus' \
--remove_non_coding 'True' \
--plot_gene_family 'RPS,RPL,mito,HB' \
--remove_gene_family 'mito' \
--min_gene_count '5' \
--min_gene_per_cell '200' \
--assay 'RNA' \
--output_path $main/analysis/1_qc \
2>&1 | tee $main/log/'01_QC_log.txt'
```
#### `Seurat_object_path`
#### `columns_metadata`
#### `species_use`
#### `remove_non_coding`
#### `plot_gene_family`
#### `remove_gene_family`
#### `min_gene_count`
#### `min_gene_per_cell`
#### `assay`

***
# Integrating datasets
```{bash, engine = 'bash', eval=F}
Rscript $script_path/02_integrate.R \
--Seurat_object_path $main/'analysis/1_qc/filt_seurat_object.rds' \
--columns_metadata $var_to_plot \
--regress $var_to_regress \
--var_genes 'seurat' \
--integration_method 'mnn,sample_id' \
--cluster_use 'NONE' \
--assay 'RNA' \
--output_path $main/'analysis/2_clustering' \
2>&1 | tee $main/log/'02_integrate_log.txt'

```
#### `Seurat_object_path`
#### `columns_metadata`
#### `regress`
#### `var_genes`
#### `integration_method`
#### `cluster_use`
#### `assay`
#### `output_path`


!()[../figures/dataset_intergration.png]


***
# Dimensionalty reduction and Clustering
```{bash, engine = 'bash', eval=F}
Rscript $script_path/03_dr_and_cluster.R \
--Seurat_object_path $main/'analysis/2_clustering/seurat_object.rds' \
--columns_metadata $var_to_plot \
--regress $var_to_regress \
--PCs_use 'var,1' \
--var_genes 'seurat' \
--dim_reduct_use 'umap' \
--cluster_use 'none' \
--cluster_method 'HC,kmeans' \
--assay 'RNA' \
--output_path $main/'analysis/2_clustering' \
2>&1 | tee $main/log/'03_dr_and_cluster_log.txt'

```
#### `Seurat_object_path`
#### `columns_metadata`
#### `regress`
#### `PCs_use`
#### `var_genes`
#### `dim_reduct_use`
#### `cluster_use`
#### `cluster_method`
#### `assay`
#### `output_path`

***
# Dimensionalty reduction and Clustering
```{bash, engine = 'bash', eval=F}
mkdir ~/Downloads/MyProject

cd ~/Downloads/MyProject

git clone https://czarnewski@bitbucket.org/scilifelab-lts/sauron.git
```

## Variable gene selection
## PCA
## UMAP



